require('render-markdown').setup({
  completions = { lsp = { enabled = true } },
  file_types = { 'markdown', 'md', 'codecompanion' },
  render_modes = true,
  code = {
    sign = true,
    border = 'thin',
    position = 'right',
    width = 'block',
    above = '▁',
    below = '▔',
    language_icon = true,
    language_name = true,
    language_info = false,
    language_left = '█',
    language_right = '█',
    language_border = '▁',
    language_pad = 0,
    left_pad = 1,
    right_pad = 1,
  },
  heading = {
    sign = false,
    width = 'block',
    -- backgrounds = {
    --   '',
    --   '',
    --   '',
    --   '',
    --   '',
    --   '',
    -- },
    left_pad = 1,
    right_pad = 0,
    position = 'right',
    icons = function(ctx)
      return (''):rep(ctx.level) .. ''
    end,
  },
})
